### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by HitagiSenjougaharaFFXIV** [Seventhxiv/Collections#8] opened 2023-11-17 20:40 UTC
Game Freeze/Crash when trying to open settings

**Comment by Seventhxiv** [comment] 2023-11-22 18:25
Would you mind recreating it and sending your dalamud.log on this discord channel so I can see what happened: https://discord.com/channels/581875019861328007/719513457988337724

Feel free to ping me there: `seventh0`

**Comment by Seventhxiv** [comment] 2023-11-22 20:08
found the root cause, some part breaks on certain languages, will push a fix

**Comment by Seventhxiv** [comment] 2023-11-25 00:07
Should be fixed now with the latest release

**Closed by Seventhxiv** 2023-11-25 00:07 UTC
